// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTgbo2CwZKAoAvl0oaC-4qjWbG_19fqU',
    appId: '1:947557351243:web:abbbab94f7da2f470072ce',
    messagingSenderId: '947557351243',
    projectId: 'deals-61803',
    authDomain: 'deals-61803.firebaseapp.com',
    storageBucket: 'deals-61803.appspot.com',
    measurementId: 'G-D7XLRY7LV9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Jzl_V0o9h52xvzRdJbzFZ6csIw9aoJ8',
    appId: '1:947557351243:ios:26aeb86e93ee53c00072ce',
    messagingSenderId: '947557351243',
    projectId: 'deals-61803',
    storageBucket: 'deals-61803.appspot.com',
    iosBundleId: 'com.example.dealsDray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Jzl_V0o9h52xvzRdJbzFZ6csIw9aoJ8',
    appId: '1:947557351243:ios:26aeb86e93ee53c00072ce',
    messagingSenderId: '947557351243',
    projectId: 'deals-61803',
    storageBucket: 'deals-61803.appspot.com',
    iosBundleId: 'com.example.dealsDray',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQTgbo2CwZKAoAvl0oaC-4qjWbG_19fqU',
    appId: '1:947557351243:web:acf55bee50044a9e0072ce',
    messagingSenderId: '947557351243',
    projectId: 'deals-61803',
    authDomain: 'deals-61803.firebaseapp.com',
    storageBucket: 'deals-61803.appspot.com',
    measurementId: 'G-90N9P9Q020',
  );

}